### PR TITLE
Updating Ruby to 3.0.5, Faraday to 2.2.0 and fix tests.

### PR DESCRIPTION
**Pull request by tccmbr**

### CODE REVIEW

**Comment by filipealc** [comment]
This is extremely necessary! Thanks for pushing the PR @tccmbr ! I will mark you @Tigraine here because I see you still work at bitmovin, if it's not you who should review PRs please push us in the right direction 🙏

**Comment by Tigraine** [comment]
> This is extremely necessary! Thanks for pushing the PR @tccmbr ! I will mark you @Tigraine here because I see you still work at bitmovin, if it's not you who should review PRs please push us in the right direction 🙏

hi @filipealc and @tccmbr ! Thanks for the contribution!
It's been a long while for this project so I have to dig out a ruby env to review the code.
But from the initial read of the PR this looks fine.
Could you please sign the [Contributor License Agreement](https://cla-assistant.io/bitmovin/bitmovin-ruby?pullRequest=26) so we can merge the PR once reviewed?

Cheers, Daniel

**Comment by tccmbr** [comment]
Hi @Tigraine , i signed the terms.

**Comment by filipealc** [comment]
Hello @Tigraine !! Any updates on this? we would love to use the official gem instead of a fork 🙏🙏🙏🙏

**Comment by yskkin** [comment]
Is bumping activesupport version necessary for this change?
`spec.add_dependency "activesupport", ">= 7.0.8"` is too strict for us to use this gem in existing Rails application.

**Pull request merged**
